### ISSUE TITLE
Content-Security-Policy doesn't allow inline script

### ISSUE THREAD

**Issue by varunyn** [Priv-Page/privpage#1]
When using <script> tag gives the following error

> Refused to load the script 'https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.js' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

Tried the meta tag but no difference in error.
> meta  http-equiv="Content-Security-Policy" content="default-src 'self'  http://* https://* 'unsafe-inline'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"

Can you guide on how to disable?
>     context.response.headers["Content-Security-Policy"] = "default-src 'self'"

**Comment by j8r** [comment]
Hello @varunyn thanks! I expected this issue to happen. You use https://privpage.net, right (you don't host your own instance)?
This security was added to prevent a site `foo--repo.privpage.net` to load resources from another one `bar--repo.privpage.net`.

The ideal would be to allow all external resources to load but those from other `privpage.net` subdomains. I am not sure how to do this.

Having a whitelist is not really an option because it won't be exhaustive.

**Comment by j8r** [comment]
It may be possible to implement a service side mitigation, I will try.

**Comment by j8r** [comment]
I removed the `Content-Security-Policy` header.
An attack to load page from an other subdomain through JS might be possible, but it will not that easy to do:
- trying this will redirect to GitHub OAuth
- embedding the page inside an iframe is forbidden
- the session cookie cannot be get/set in JS.
