### ISSUE TITLE
Certificate not valid

### ISSUE THREAD

**Issue by postylem** [Priv-Page/privpage#16]
Thank you for this useful service! I just started using it, and it seems the root certificate is expired. I don't understand how such things work, and I see that something similar has been recently raised in #10, #12, and #15, and apparently addressed, so perhaps it is on my end somehow?

But I get warning messages when trying to visit any `*.github.privpage.net` sites, and looking at the certificate, this is what I see:
![Screen Shot 2021-10-23 at 15 30 40](https://user-images.githubusercontent.com/5202957/138569184-65d6e64d-e835-4134-963e-8ec0d643f467.png)

Excuse me please if this is my ignorance, and I should just be flushing some cache.

**Comment by j8r** [comment]
I don't have this issue on my side. You may not use an up-to-date OpenSSL version, see https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Comment by postylem** [comment]
Ok.  Interesting.  I notice I get the same warning when I access for instance https://priv-page--test.github.privpage.net on my phone using data.  Can this possibly be an issue on my end?

**Comment by j8r** [comment]
Maybe an Apple-related issue about handling the certificate. Dont't have it this on Android either.

Anyway I'll likely shut down the service in the future, since I spend time and money for no advantage... Or maybe making people HTTPS access paid 🤔

Sorry for now I do the bare minimum and have no incentive to spend much time, quite busy curently.

**Comment by postylem** [comment]
Totally understand. Thanks for putting it up!
