### ISSUE TITLE
Support for multiple branches

### ISSUE THREAD

**Issue by luisfavila** [Priv-Page/privpage#2]
Hi,

It would pretty nice to have multiple branches support. On my use case, I've made a private repo just for privpage and it would be great if I could take advantage of different branches to show different versions of the same internal documentation. This could probably be achieved with a subdomain.

Let me know your toughts :)

**Comment by j8r** [comment]
It is a good idea, thanks for the suggestion @luisfavila .
It may be possible with a subdomain, but there is no really incentive security/simplicity wise.

Another option is to use a path, but it would conflicts with the existing ones from the standard `privpage` branch.

**Comment by j8r** [comment]
I don't see another way to do this without adding another element to the user repository subdomain. The delimiter being `--`, we'll have: `user--repo--branch.github.privpage.net`.
Sounds good to you?
Of course, `--` would be forbidden, like already for the user and repository name.

Having a sub-sub-sub domain is not a good option, because of the need of registering DNS and generating HTTPS certificates.

**Comment by luisfavila** [comment]
Yes, it works :)
With subdomains you'd have to use a wildcard certificate and some DNS provider that supports wildcard entries (i.e. Cloudflare)

**Comment by j8r** [comment]
Yes, the point is it is already done (`*.github.privpage.net`), double wildcard is not possible.
I'm working on my above proposal then 😉

**Comment by j8r** [comment]
@luisfavila Last thing, why don't you organize the `privpage` branch with directories for each version?
A rather significant limitations of using subdomains is that dots `.` are forbidden.

**Comment by luisfavila** [comment]
Yeah, I thought about it but it would go against the idea of using git as version control and you'd duplicate a lot of contenr

**Comment by luisfavila** [comment]
The --branch seems to be the easiest and best way to implement :)
